"""add_organization_id_and_enterprise_tables

Revision ID: 8d96c17e522c
Revises: efe9dee142f9
Create Date: 2026-06-16 16:43:57.678257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d96c17e522c'
down_revision: Union[str, None] = 'efe9dee142f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_organization_id'), ['organization_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_organization_id'), ['organization_id'], unique=False)

    op.create_table('integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_organization_id'), ['organization_id'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_organization_id'), ['organization_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('agent_meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agent_meetings_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('ai_batch_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_batch_jobs_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('api_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_api_credentials_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_business_profiles_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_candidates_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('content_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_content_posts_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contracts_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invitations_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('provider_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_provider_usage_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tickets_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('provider_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_usage_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('content_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_posts_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_profiles_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('api_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_credentials_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('ai_batch_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_batch_jobs_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('agent_meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_meetings_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_organization_id'))
        batch_op.drop_index(batch_op.f('ix_messages_id'))

    op.drop_table('messages')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_organization_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_id'))

    op.drop_table('meetings')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_integrations_id'))

    op.drop_table('integrations')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))

    op.drop_table('contacts')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_organization_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
