"""Add sales and support emails

Revision ID: 9a1b2c3d4e5f
Revises: 375b132b27a8
Create Date: 2026-06-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1b2c3d4e5f'
down_revision = '375b132b27a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('sales_emails', sa.JSON(), nullable=True))
    op.add_column('business_profiles', sa.Column('support_emails', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'support_emails')
    op.drop_column('business_profiles', 'sales_emails')
    # ### end Alembic commands ###
